tap "dbcli/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/services"
tap "stevenberg/tap"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
brew "ansible"
brew "ansible-lint"
brew "autojump"
brew "autopep8"
brew "bash"
brew "bat"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "composer"
brew "cppcheck"
brew "crystal-lang"
brew "dfc"
brew "direnv"
brew "dos2unix"
brew "editorconfig"
brew "entr"
brew "exa"
brew "exiftool"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gitlint"
brew "gitsh"
brew "go"
brew "graphviz"
brew "hivemind"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "isort"
brew "jemalloc"
brew "jpegoptim"
brew "jq"
brew "jsonlint"
brew "laravel-installer"
brew "laravel-zero-installer"
brew "lesspipe"
brew "libffi"
brew "libmemcached"
brew "libsodium"
brew "libyaml"
brew "litecli"
brew "lumen-installer"
brew "magic-wormhole"
brew "mas"
brew "memcached"
brew "mercurial"
brew "mkcert"
brew "multimarkdown"
brew "mysql"
brew "mycli"
brew "ncdu"
brew "nim"
brew "nmap"
brew "node"
brew "nss"
brew "openssl"
brew "overmind"
brew "perl6"
brew "pgcli"
brew "php"
brew "php@7.2"
brew "php@7.3"
brew "php-cs-fixer"
brew "pipenv"
brew "pkg-config"
brew "png2ico"
brew "pngcrush"
brew "postgresql"
brew "prettyping"
brew "proselint"
brew "pstree"
brew "psysh"
brew "pylint"
brew "python"
brew "rcm"
brew "redis"
brew "rename"
brew "ripgrep"
brew "ruby-install"
brew "rubyfmt"
brew "shellcheck"
brew "shfmt"
brew "spiped"
brew "tarsnap"
brew "tidy-html5"
brew "tldr"
brew "trash"
brew "tree"
brew "typescript"
brew "universal-ctags", args: ["HEAD"]
brew "unrar"
brew "vcprompt"
brew "vim"
brew "watch"
brew "wget"
brew "vint"
brew "xsv"
brew "yamllint"
brew "yarn"
brew "zlib"
mas "1Blocker", id: 1107421413
mas "ColorSnapper2", id: 969418666
mas "Contrast", id: 1254981365
mas "Icon Slate", id: 439697913
mas "iStat Mini", id: 927292435
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "Speedtest", id: 1153157709
mas "StopTheMadness", id: 1376402589
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
