# frozen_string_literal: true

tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
brew "git", args: [
  "with-blk-sha1",
  "with-pcre",
  "with-persistent-https",
]
brew "ansible"
brew "ansible-lint"
brew "autojump"
brew "bash"
brew "bat"
brew "clang-format"
brew "cmake"
brew "cppcheck"
brew "crystal-lang"
brew "dfc"
brew "direnv"
brew "dnsmasq"
brew "dos2unix"
brew "editorconfig"
brew "entr"
brew "exa"
brew "exiftool"
brew "fd"
brew "fd"
brew "fish"
brew "fzf"
brew "gitsh"
brew "graphviz"
brew "hivemind"
brew "htop", args: ["with-ncurses"]
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jemalloc"
brew "jpegoptim"
brew "jq"
brew "lesspipe", args: ["with-syntax-highlighting"]
brew "libffi"
brew "libsodium"
brew "libyaml"
brew "mariadb"
brew "memcached"
brew "mercurial"
brew "multimarkdown"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "openssl"
brew "overmind"
brew "perl6"
brew "php"
brew "php@5.6"
brew "php@7.0"
brew "php@7.1"
brew "pkg-config"
brew "png2ico"
brew "pngcrush"
brew "postgresql"
brew "prettyping"
brew "proselint"
brew "pstree"
brew "python"
brew "rcm"
brew "redis"
brew "rename"
brew "ripgrep"
brew "ruby-install"
brew "shellcheck"
brew "shfmt"
brew "spiped"
brew "thefuck"
brew "tidy-html5"
brew "tldr"
brew "trash"
brew "tree"
brew "universal-ctags", args: ["HEAD"]
brew "unrar"
brew "vcprompt"
brew "vim"
brew "watch"
brew "wget"
brew "xsv"
brew "yarn", args: ["without-node"]
