command_timeout = 1000

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[env_var]
disabled = true

[gcloud]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true
