# shellcheck shell=bash

shopt -s autocd
shopt -s checkhash
shopt -s checkjobs
shopt -s checkwinsize
shopt -s cmdhist
shopt -s extglob
shopt -s globstar
shopt -s histappend
shopt -s histverify
shopt -s lithist

HISTCONTROL='ignoreboth'
HISTSIZE=-1

export EDITOR='vim'
export LC_ALL='en_US.UTF-8'
export LESS='-F -g -i -r -w -X -z-3'
export LESS_ADVANCED_PREPROCESSOR=1
export VISUAL=$EDITOR

if [ "$(uname -s)" = 'Darwin' ]; then
    HOMEBREW_PREFIX=/opt/homenbrew
else
    HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
fi

if [ -x $HOMEBREW_PREFIX/bin/brew ]; then
    export HOMEBREW_INSTALL_CLEANUP=1
    eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
fi

if command -v lesspipe >/dev/null 2>&1; then
    eval "$(lesspipe)"
fi
if command -v lesspipe.sh >/dev/null 2>&1; then
    eval "$(lesspipe.sh)"
fi

CDPATH=.
for path in $HOME/Development/Projects $HOME/Development/Excel/Projects; do
    if [ -d "$path" ]; then
        CDPATH="$CDPATH:$path"
    fi
done
export CDPATH

for path in $HOME/bin $HOMEBREW_PREFIX/opt/python/libexec $HOME/.composer/vendor/bin; do
    if [ -d "$path" ]; then
        PATH=$path:$PATH
    fi
done

if [ -d "$HOME"/.cargo ]; then
    # shellcheck source=/dev/null
    source "$HOME"/.cargo/env
fi

if [ -d $HOMEBREW_PREFIX/opt/go/libexec ] && [ -d "$HOME"/Development/Go ]; then
    export GOPATH="$HOME"/Development/Go
    export GOROOT=$HOMEBREW_PREFIX/opt/go/libexec
    PATH=$HOME/Development/Go/bin:$PATH
fi

if command -v >/dev/null 2>&1 open; then
    export BROWSER=open
fi

if command -v >/dev/null 2>&1 fzf; then
    export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
fi

if command -v >/dev/null 2>&1 rbenv; then
    export RUBY_CONFIGURE_OPTS='--with-jemalloc'
    eval "$(rbenv init - bash)"
fi

if command -v >/dev/null 2>&1 direnv; then
    eval "$(direnv hook bash)"
fi

shopt -s nullglob
for config in "$HOME"/.config/bash/*.bash; do
    # shellcheck source=/dev/null
    source "$config"
done
shopt -u nullglob

if [[ $- == *i* ]]; then
    BASE16_SHELL_PATH="$HOME"/.config/base16-shell
    # shellcheck source=/dev/null
    source "$BASE16_SHELL_PATH"/profile_helper.sh

    function precommand() {
        if command -v >/dev/null 2>&1 spwd; then
                echo -ne "\033]0; $(spwd) \007"
        fi
        if [ "$(light-or-dark)" = light ]; then
            _base16 "$BASE16_SHELL_PATH/scripts/base16-default-light.sh" default-light
        else
            _base16 "$BASE16_SHELL_PATH/scripts/base16-default-dark.sh" default-dark
        fi
    }

    if command -v >/dev/null 2>&1 starship; then
        eval "$(starship init bash)"
        export starship_precmd_user_func='precommand'
    else
        export PROMPT_COMMAND='precommand'
    fi

    if [ "$TERM_PROGRAM" = 'iTerm.app' ]; then
        # shellcheck source=/dev/null
        source "$HOME"/.iterm2_shell_integration.bash
    fi
fi

alias grep='grep --color=auto'
if command -v >/dev/null 2>&1 exa; then
    alias ls='exa'
fi
alias ll='ls -l'
alias la='ll -a'
