# shellcheck shell=bash

# shellcheck source=/dev/null
source "$HOME/.config/bash/settings.bash"

export COMPONENTS=(
    homebrew
    path
    starship
    base16
    aliases
    cdpath
    direnv
    fzf
    golang
    lesspipe
    rm
    ruby
    rust
)

export ADD_PATHS=(
    "$HOME/bin"
    "$HOMEBREW_PREFIX/opt/python/libexec"
    "$HOME/.composer/vendor/bin"
)

export ADD_CDPATHS=(
    "$HOME/Development/Projects"
    "$HOME/Development/Excel/Projects"
)

# shellcheck source=/dev/null
source "$HOME/.config/bash/components.bash"
