# shellcheck shell=bash

shopt -s autocd
shopt -s checkhash
shopt -s checkjobs
shopt -s checkwinsize
shopt -s cmdhist
shopt -s extglob
shopt -s globstar
shopt -s histappend
shopt -s histverify
shopt -s lithist

HISTCONTROL='ignoreboth'
HISTSIZE=-1

export BROWSER='open'
export EDITOR='vim'
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'
export GOPATH="$HOME/Development/go"
export GOROOT='/usr/local/opt/go/libexec'
export HOMEBREW_INSTALL_CLEANUP=1
export LC_ALL='en_US.UTF-8'
export LESS='-F -g -i -r -w -X -z-3'
export LESS_ADVANCED_PREPROCESSOR=1
export RUBY_CONFIGURE_OPTS='--with-jemalloc'
export VISUAL=$EDITOR

if [[ $- == *i* ]]; then
    # shellcheck source=/dev/null
    source "$HOME/.iterm2_shell_integration.bash"
    eval "$("$HOME"/.config/base16-shell/profile_helper.sh)"

    eval "$(lesspipe.sh)"

    eval "$(starship init bash)"
fi

# shellcheck source=/dev/null
source  "$HOME/.cargo/env"

eval "$(rbenv init - bash)"

eval "$(direnv hook bash)"

shopt -s nullglob
for config in "$HOME"/.config/bash/*.bash; do
    # shellcheck source=/dev/null
    source "$config"
done
shopt -u nullglob

alias grep='grep --color=auto'
alias hub='git'
alias ls='exa'
alias ll='ls -l'
alias la='ll -a'
